name: Broken Link Checker
on:
  push:
    paths:
      - '**/*.md'
      - '**/*.html'
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.html'
jobs:
  linkchecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Check for broken links
        uses: lycheeverse/lychee-action@v2.5.0
        with:
          args: >
            --verbose
            --no-progress
            --exclude '\{\{.*\}\}'
            --exclude-path '_layouts'
            '**/*.md'
            '**/*.html'
