name: Lint HTML

on:
  push:
    paths:
      - '**/*.html'
  pull_request:
    paths:
      - '**/*.html'

jobs:
  htmllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install htmllint CLI
        run: npm install htmllint-cli --save-dev

      - name: Run HTML Linter
        run: npx htmllint '_layouts/default.html'