name: Lint Markdown
on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
